/**:
  ros__parameters:
    constraints:
      hard:
        max_curvature: 0.3
        min_curvature: -0.3
      soft:
        lateral_deviation_weight: 0.1
        longitudinal_deviation_weight: 1.0
        jerk_weight: 1.0
        length_weight: -1.0  # negative weight to turn the length cost into a reward
        curvature_weight: 1.0
    sampling:
      enable_frenet: False
      enable_bezier: True
      resolution: 0.1
      minimum_committed_length: 5.0
      reuse_max_length_max: 50.0
      reuse_samples: 2
      reuse_max_deviation: 1.0  # TODO(Maxime CLEMENT): use parameter from the lateral_deviation_checker
      target_lengths: [40.0, 60.0]
      frenet:
        target_lateral_positions: [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
        target_lateral_velocities: [-0.1, 0.0, 0.1]
        target_lateral_accelerations: [-0.1, 0.0, 0.1]
      bezier:
        nb_k: 3
        mk_min: 0.0
        mk_max: 10.0
        nb_t: 10
        mt_min: 0.3
        mt_max: 1.7
