/**:
  ros__parameters:
    fallback_trajectory_timeout: 0.5  # [s] age below which a fallback trajectory can be used
    preprocessing:
      force_zero_initial_deviation: True  # if true, initial planning starts from the reference path
      force_zero_initial_heading: True # if true, initial planning starts with a heading aligned with the reference path
      smooth_reference_trajectory: True  # if true, the reference trajectory is smoothed before being used for planning
    constraints:
      hard:
        max_curvature: 0.1
        min_curvature: -0.1
      soft:
        lateral_deviation_weight: 0.1
        longitudinal_deviation_weight: 1.0
        jerk_weight: 1.0
        length_weight: -1.0  # negative weight to turn the length cost into a reward
        curvature_weight: 1.0
    sampling:
      enable_frenet: True
      enable_bezier: True
      resolution: 0.1
      minimum_committed_length: 5.0
      reuse_max_length_max: 50.0
      reuse_samples: 2
      reuse_max_deviation: 1.0
      target_lengths: [40.0, 60.0]
      frenet:
        target_lateral_positions: [-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5]
        target_lateral_velocities: [-0.1, 0.0, 0.1]
        target_lateral_accelerations: [0.0]
      bezier:
        nb_k: 3
        mk_min: 0.0
        mk_max: 10.0
        nb_t: 10
        mt_min: 0.3
        mt_max: 1.7
